version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=015838347042.dkr.ecr.us-east-1.amazonaws.com/sample-demo-python-19
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $REPOSITORY_URI
      - echo $COMMIT_HASH
      - echo $IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...          
      - docker build -t myapp:latest .
      - docker tag myapp:latest 015838347042.dkr.ecr.us-east-1.amazonaws.com/sample-demo-python-19
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 015838347042.dkr.ecr.us-east-1.amazonaws.com/sample-demo-python-19
